# Generated by Django 3.2.15 on 2022-09-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('crt_ts', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upd_ts', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.IntegerField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
    ]
